# encoding: UTF-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Environment variables (ENV['...']) are set in the file config/application.yml.
# See http://railsapps.github.io/rails-environment-variables.html

puts 'ROLES'
YAML.load(ENV['ROLES']).each do |role|
  Role.find_or_create_by_name({ :name => role }, :without_protection => true)
  puts 'role: ' << role
end
puts 'DEFAULT USERS'

# admin = User.find_or_create_by_email :name =>, :email => ENV['ADMIN_EMAIL'].dup, :password => ENV['ADMIN_PASSWORD'].dup, :password_confirmation => ENV['ADMIN_PASSWORD'].dup
# puts 'user: ' << admin.name
# admin.add_role :admin


users[1] = User.create!(:email =>"user1@gmail.com", :password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Nick",:last_name => " Lowe"); user = users[1]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[2] = User.create!(:email =>"user2@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Yvonne",:last_name => " Woods");user = users[2]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[3] = User.create!(:email =>"user3@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Laura",:last_name => " Barber");user = users[3]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[4] = User.create!(:email =>"user4@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Gwen",:last_name => " Blair");user = users[4]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[5] = User.create!(:email =>"user5@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Geoffrey",:last_name => " Wilkins");user = users[5]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[6] = User.create!(:email =>"user6@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Janie",:last_name => " Doyle");user = users[6]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[7] = User.create!(:email =>"user7@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Dustin",:last_name => " Spencer");user = users[7]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[8] = User.create!(:email =>"user8@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Geneva",:last_name => " Schultz");user = users[8]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[9] = User.create!(:email =>"user9@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Margaret",:last_name => " Stewart");user = users[9]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[10] = User.create!(:email =>"user10@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Bethany",:last_name => " Hayes");user = users[10]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[11] = User.create!(:email =>"user11@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Mable",:last_name => " Francis");user = users[11]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[12] = User.create!(:email =>"user12@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Wendy",:last_name => " Thornton");user = users[12]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[13] = User.create!(:email =>"user13@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Horace",:last_name => " Wong");user = users[13]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[14] = User.create!(:email =>"user14@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Dora",:last_name => " Graham");user = users[14]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[15] = User.create!(:email =>"user15@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Cecil",:last_name => " Riley");user = users[15]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[16] = User.create!(:email =>"user16@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Eva",:last_name => " Gonzalez");user = users[16]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[17] = User.create!(:email =>"user17@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Bennie",:last_name => " Ramos");user = users[17]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[18] = User.create!(:email =>"user18@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Phillip",:last_name => " Hawkins");user = users[18]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[19] = User.create!(:email =>"user19@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Otis",:last_name => " Casey");user = users[19]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[20] = User.create!(:email =>"user20@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Juanita",:last_name => " Mendoza");user = users[20]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[21] = User.create!(:email =>"user21@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Max",:last_name => " Beck");user = users[21]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[22] = User.create!(:email =>"user22@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Charlene",:last_name => " Newman");user = users[22]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[23] = User.create!(:email =>"user23@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Arlene",:last_name => " Larson");user = users[23]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[24] = User.create!(:email =>"user24@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Amy",:last_name => " Wilson");user = users[24]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[25] = User.create!(:email =>"user25@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Hilda",:last_name => " Estrada");user = users[25]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[26] = User.create!(:email =>"user26@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Maggie",:last_name => " King");user = users[26]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[27] = User.create!(:email =>"user27@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Adam",:last_name => " Pena");user = users[27]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[28] = User.create!(:email =>"user28@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Sara",:last_name => " Carlson");user = users[28]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[29] = User.create!(:email =>"user29@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Jana",:last_name => " Morris");user = users[29]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[30] = User.create!(:email =>"user30@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Kenneth",:last_name => " Cobb");user = users[30]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[31] = User.create!(:email =>"user31@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Miguel",:last_name => " Ryan");user = users[31]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[32] = User.create!(:email =>"user32@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Diana",:last_name => " Becker");user = users[32]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[33] = User.create!(:email =>"user33@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Adrian",:last_name => " Christensen");user = users[33]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[34] = User.create!(:email =>"user34@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Shannon",:last_name => " Duncan");user = users[34]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[35] = User.create!(:email =>"user35@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Tiffany",:last_name => " Marshall");user = users[35]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[36] = User.create!(:email =>"user36@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Bernadette",:last_name => " Rhodes");user = users[36]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[37] = User.create!(:email =>"user37@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Jacqueline",:last_name => " Hubbard");user = users[37]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[38] = User.create!(:email =>"user38@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Sabrina",:last_name => " Pratt");user = users[38]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[39] = User.create!(:email =>"user39@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Gordon",:last_name => " Cummings");user = users[39]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[40] = User.create!(:email =>"user40@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Robyn",:last_name => " Mccoy");user = users[40]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[41] = User.create!(:email =>"user41@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Levi",:last_name => " Sutton");user = users[41]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[42] = User.create!(:email =>"user42@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Merle",:last_name => " Fowler");user = users[42]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[43] = User.create!(:email =>"user43@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Gabriel",:last_name => " Day");user = users[43]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[44] = User.create!(:email =>"user44@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Ira",:last_name => " Johnston");user = users[44]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[45] = User.create!(:email =>"user45@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Bridget",:last_name => " Haynes");user = users[45]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[46] = User.create!(:email =>"user46@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Luis",:last_name => " Quinn");user = users[46]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[47] = User.create!(:email =>"user47@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Amos",:last_name => " Rodgers");user = users[47]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[48] = User.create!(:email =>"user48@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Carl",:last_name => " Fletcher");user = users[48]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[49] = User.create!(:email =>"user49@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Maryann",:last_name => " Ramsey");user = users[49]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[50] = User.create!(:email =>"user50@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Josefina",:last_name => " Nash");user = users[50]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[51] = User.create!(:email =>"user51@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Joe",:last_name => " Bryant");user = users[51]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[52] = User.create!(:email =>"user52@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Frankie",:last_name => " Mendez");user = users[52]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[53] = User.create!(:email =>"user53@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Marlene",:last_name => " Love");user = users[53]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[54] = User.create!(:email =>"user54@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Allison",:last_name => " Mccormick");user = users[54]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[55] = User.create!(:email =>"user55@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Abel",:last_name => " Byrd");user = users[55]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[56] = User.create!(:email =>"user56@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Willie",:last_name => " Perry");user = users[56]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[57] = User.create!(:email =>"user57@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Rosemarie",:last_name => " Santiago");user = users[57]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[58] = User.create!(:email =>"user58@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Francis",:last_name => " Torres");user = users[58]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[59] = User.create!(:email =>"user59@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Donna",:last_name => " Rowe");user = users[59]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[60] = User.create!(:email =>"user60@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Spencer",:last_name => " Frank");user = users[60]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[61] = User.create!(:email =>"user61@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Tanya",:last_name => " Lewis");user = users[61]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[62] = User.create!(:email =>"user62@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Loren",:last_name => " Vaughn");user = users[62]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[63] = User.create!(:email =>"user63@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Rita",:last_name => " Martin");user = users[63]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[64] = User.create!(:email =>"user64@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Elijah",:last_name => " Nichols");user = users[64]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[65] = User.create!(:email =>"user65@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Kristi",:last_name => " Holmes");user = users[65]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[66] = User.create!(:email =>"user66@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Brandy",:last_name => " Mullins");user = users[66]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[67] = User.create!(:email =>"user67@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Michele",:last_name => " Guerrero");user = users[67]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[68] = User.create!(:email =>"user68@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Kristopher",:last_name => " Alexander");user = users[68]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[69] = User.create!(:email =>"user69@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Noel",:last_name => " Dawson");user = users[69]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[70] = User.create!(:email =>"user70@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Terry",:last_name => " Barton");user = users[70]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[71] = User.create!(:email =>"user71@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Natalie",:last_name => " Herrera");user = users[71]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[72] = User.create!(:email =>"user72@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Erica",:last_name => " Price");user = users[72]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[73] = User.create!(:email =>"user73@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Edith",:last_name => " Ortega");user = users[73]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[74] = User.create!(:email =>"user74@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Rodolfo",:last_name => " Olson");user = users[74]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[75] = User.create!(:email =>"user75@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Juan",:last_name => " Collier");user = users[75]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[76] = User.create!(:email =>"user76@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "David",:last_name => " Nguyen");user = users[76]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[77] = User.create!(:email =>"user77@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Dan",:last_name => " Arnold");user = users[77]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[78] = User.create!(:email =>"user78@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Glen",:last_name => " Williamson");user = users[78]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[79] = User.create!(:email =>"user79@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Don",:last_name => " Walters");user = users[79]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[80] = User.create!(:email =>"user80@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Taylor",:last_name => " Padilla");user = users[80]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[81] = User.create!(:email =>"user81@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Bernard",:last_name => " Bryan");user = users[81]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[82] = User.create!(:email =>"user82@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Chester",:last_name => " Matthews");user = users[82]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[83] = User.create!(:email =>"user83@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Loretta",:last_name => " Wright");user = users[83]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[84] = User.create!(:email =>"user84@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Dexter",:last_name => " Welch");user = users[84]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[85] = User.create!(:email =>"user85@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Vera",:last_name => " Reeves");user = users[85]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[86] = User.create!(:email =>"user86@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Marianne",:last_name => " Castillo");user = users[86]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[87] = User.create!(:email =>"user87@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Wesley",:last_name => " Marsh");user = users[87]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[88] = User.create!(:email =>"user88@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Katherine",:last_name => " Bass");user = users[88]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[89] = User.create!(:email =>"user89@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Rochelle",:last_name => " Cohen");user = users[89]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[90] = User.create!(:email =>"user90@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Robert",:last_name => " Norris");user = users[90]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[91] = User.create!(:email =>"user91@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Mildred",:last_name => " Ball");user = users[91]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[92] = User.create!(:email =>"user92@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Martha",:last_name => " Howell");user = users[92]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[93] = User.create!(:email =>"user93@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Rosa",:last_name => " Porter");user = users[93]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[94] = User.create!(:email =>"user94@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Ebony",:last_name => " Ruiz");user = users[94]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[95] = User.create!(:email =>"user95@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Sergio",:last_name => " Sandoval");user = users[95]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[96] = User.create!(:email =>"user96@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Diane",:last_name => " Medina");user = users[96]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[97] = User.create!(:email =>"user97@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Lynn",:last_name => " Chavez");user = users[97]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[98] = User.create!(:email =>"user98@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Marilyn",:last_name => " Hughes");user = users[98]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[99] = User.create!(:email =>"user99@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Benny",:last_name => " Obrien");user = users[99]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[100] = User.create!(:email =>"user100@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Kayla",:last_name => " Evans");user = users[100]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[101] = User.create!(:email =>"user101@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Garrett",:last_name => " Maxwell");user = users[101]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[102] = User.create!(:email =>"user102@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Rex",:last_name => " Murphy");user = users[102]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[103] = User.create!(:email =>"user103@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Juana",:last_name => " Wagner");user = users[103]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[104] = User.create!(:email =>"user104@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Terrell",:last_name => " Peters");user = users[104]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[105] = User.create!(:email =>"user105@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Santos",:last_name => " Daniel");user = users[105]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[106] = User.create!(:email =>"user106@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Todd",:last_name => " Foster");user = users[106]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[107] = User.create!(:email =>"user107@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Sheldon",:last_name => " Holt");user = users[107]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[108] = User.create!(:email =>"user108@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Terence",:last_name => " Carson");user = users[108]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[109] = User.create!(:email =>"user109@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Faye",:last_name => " Rogers");user = users[109]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[110] = User.create!(:email =>"user110@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Lydia",:last_name => " Roy");user = users[110]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[111] = User.create!(:email =>"user111@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Freddie",:last_name => " Greene");user = users[111]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[112] = User.create!(:email =>"user112@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Wm",:last_name => " Payne");user = users[112]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[113] = User.create!(:email =>"user113@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Felix",:last_name => " Ortiz");user = users[113]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[114] = User.create!(:email =>"user114@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Wallace",:last_name => " Brooks");user = users[114]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[115] = User.create!(:email =>"user115@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Darrel",:last_name => " Goodwin");user = users[115]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[116] = User.create!(:email =>"user116@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Andres",:last_name => " Newman");user = users[116]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[117] = User.create!(:email =>"user117@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Silvia",:last_name => " Malone");user = users[117]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[118] = User.create!(:email =>"user118@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Alan",:last_name => " Austin");user = users[118]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[119] = User.create!(:email =>"user119@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Cecilia",:last_name => " Walsh");user = users[119]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[120] = User.create!(:email =>"user120@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Janice",:last_name => " Burns");user = users[120]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[121] = User.create!(:email =>"user121@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Eugene",:last_name => " Hawkins");user = users[121]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[122] = User.create!(:email =>"user122@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Jan",:last_name => " Pittman");user = users[122]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[123] = User.create!(:email =>"user123@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Donald",:last_name => " Washington");user = users[123]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[124] = User.create!(:email =>"user124@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Bobbie",:last_name => " Estrada");user = users[124]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[125] = User.create!(:email =>"user125@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Rodney",:last_name => " Mcdaniel");user = users[125]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[126] = User.create!(:email =>"user126@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Dennis",:last_name => " Stevenson");user = users[126]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[127] = User.create!(:email =>"user127@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Hope",:last_name => " Chapman");user = users[127]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[128] = User.create!(:email =>"user128@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Willis",:last_name => " Rios");user = users[128]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[129] = User.create!(:email =>"user129@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Judith",:last_name => " Robertson");user = users[129]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[130] = User.create!(:email =>"user130@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Ruben",:last_name => " Sanchez");user = users[130]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[131] = User.create!(:email =>"user131@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Randy",:last_name => " Barrett");user = users[131]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[132] = User.create!(:email =>"user132@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Kay",:last_name => " Burke");user = users[132]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[133] = User.create!(:email =>"user133@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Dawn",:last_name => " Gordon");user = users[133]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[134] = User.create!(:email =>"user134@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Ollie",:last_name => " Colon");user = users[134]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[135] = User.create!(:email =>"user135@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Clayton",:last_name => " Lynch");user = users[135]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[136] = User.create!(:email =>"user136@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Lindsay",:last_name => " Mckinney");user = users[136]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[137] = User.create!(:email =>"user137@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Felipe",:last_name => " Hayes");user = users[137]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[138] = User.create!(:email =>"user138@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Edith",:last_name => " Cunningham");user = users[138]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[139] = User.create!(:email =>"user139@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Verna",:last_name => " Lucas");user = users[139]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[140] = User.create!(:email =>"user140@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Clifton",:last_name => " Tran");user = users[140]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[141] = User.create!(:email =>"user141@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Lola",:last_name => " Cannon");user = users[141]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[142] = User.create!(:email =>"user142@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Ben",:last_name => " Gregory");user = users[142]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[143] = User.create!(:email =>"user143@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Celia",:last_name => " Black");user = users[143]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[144] = User.create!(:email =>"user144@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Russell",:last_name => " Greer");user = users[144]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[145] = User.create!(:email =>"user145@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Marilyn",:last_name => " Williamson");user = users[145]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[146] = User.create!(:email =>"user146@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Austin",:last_name => " Alvarado");user = users[146]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[147] = User.create!(:email =>"user147@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Javier",:last_name => " Lee");user = users[147]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[148] = User.create!(:email =>"user148@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Eva",:last_name => " Hopkins");user = users[148]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[149] = User.create!(:email =>"user149@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Arthur",:last_name => " Romero");user = users[149]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[150] = User.create!(:email =>"user150@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Tina",:last_name => " Dean");user = users[150]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[151] = User.create!(:email =>"user151@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Laurence",:last_name => " Palmer");user = users[151]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[152] = User.create!(:email =>"user152@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Julius",:last_name => " Singleton");user = users[152]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[153] = User.create!(:email =>"user153@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Wesley",:last_name => " Adams");user = users[153]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[154] = User.create!(:email =>"user154@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Yvonne",:last_name => " Floyd");user = users[154]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[155] = User.create!(:email =>"user155@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Ernesto",:last_name => " Frazier");user = users[155]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[156] = User.create!(:email =>"user156@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Carole",:last_name => " Blair");user = users[156]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[157] = User.create!(:email =>"user157@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Kerry",:last_name => " Reynolds");user = users[157]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[158] = User.create!(:email =>"user158@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Ida",:last_name => " Scott");user = users[158]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[159] = User.create!(:email =>"user159@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Homer",:last_name => " Carlson");user = users[159]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[160] = User.create!(:email =>"user160@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Virginia",:last_name => " Gomez");user = users[160]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[161] = User.create!(:email =>"user161@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Rufus",:last_name => " Thomas");user = users[161]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[162] = User.create!(:email =>"user162@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Gail",:last_name => " Nichols");user = users[162]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[163] = User.create!(:email =>"user163@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Inez",:last_name => " Barnes");user = users[163]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[164] = User.create!(:email =>"user164@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Vernon",:last_name => " Stephens");user = users[164]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[165] = User.create!(:email =>"user165@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Annie",:last_name => " Blake");user = users[165]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[166] = User.create!(:email =>"user166@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Allan",:last_name => " King");user = users[166]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[167] = User.create!(:email =>"user167@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Lula",:last_name => " Carter");user = users[167]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[168] = User.create!(:email =>"user168@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Frances",:last_name => " Wood");user = users[168]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[169] = User.create!(:email =>"user169@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Toby",:last_name => " Wong");user = users[169]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[170] = User.create!(:email =>"user170@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Cecil",:last_name => " Hodges");user = users[170]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[171] = User.create!(:email =>"user171@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Arlene",:last_name => " Guzman");user = users[171]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[172] = User.create!(:email =>"user172@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Tyrone",:last_name => " Richardson");user = users[172]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[173] = User.create!(:email =>"user173@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Mack",:last_name => " Martinez");user = users[173]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[174] = User.create!(:email =>"user174@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Camille",:last_name => " Barber");user = users[174]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[175] = User.create!(:email =>"user175@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Jean",:last_name => " Burton");user = users[175]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[176] = User.create!(:email =>"user176@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Wilbur",:last_name => " Fields");user = users[176]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[177] = User.create!(:email =>"user177@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Geneva",:last_name => " Crawford");user = users[177]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[178] = User.create!(:email =>"user178@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Beulah",:last_name => " Fletcher");user = users[178]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[179] = User.create!(:email =>"user179@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Jeannie",:last_name => " Hale");user = users[179]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[180] = User.create!(:email =>"user180@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Luis",:last_name => " Miles");user = users[180]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[181] = User.create!(:email =>"user181@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Louis",:last_name => " Larson");user = users[181]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[182] = User.create!(:email =>"user182@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Ann",:last_name => " Drake");user = users[182]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[183] = User.create!(:email =>"user183@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Esther",:last_name => " Schwartz");user = users[183]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[184] = User.create!(:email =>"user184@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Nicole",:last_name => " Christensen");user = users[184]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[185] = User.create!(:email =>"user185@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Sheryl",:last_name => " Hampton");user = users[185]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[186] = User.create!(:email =>"user186@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Elijah",:last_name => " Rose");user = users[186]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[187] = User.create!(:email =>"user187@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Herbert",:last_name => " Phelps");user = users[187]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[188] = User.create!(:email =>"user188@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Leonard",:last_name => " Griffith");user = users[188]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[189] = User.create!(:email =>"user189@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Norma",:last_name => " Padilla");user = users[189]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[190] = User.create!(:email =>"user190@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Paul",:last_name => " Porter");user = users[190]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[191] = User.create!(:email =>"user191@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Lionel",:last_name => " Warner");user = users[191]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[192] = User.create!(:email =>"user192@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Ron",:last_name => " Jenkins");user = users[192]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[193] = User.create!(:email =>"user193@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Terry",:last_name => " Shaw");user = users[193]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[194] = User.create!(:email =>"user194@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Jim",:last_name => " Harrison");user = users[194]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[195] = User.create!(:email =>"user195@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Glenda",:last_name => " Jacobs");user = users[195]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[196] = User.create!(:email =>"user196@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Steven",:last_name => " Sherman");user = users[196]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[197] = User.create!(:email =>"user197@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Judy",:last_name => " Vargas");user = users[197]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[198] = User.create!(:email =>"user198@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Sean",:last_name => " Lloyd");user = users[198]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[199] = User.create!(:email =>"user199@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Diana",:last_name => " Armstrong");user = users[199]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save
users[200] = User.create!(:email =>"user200@gmail.com",:password =>"foobar123",:city =>"Harbor Springs",:state =>"Michigan",:first_name => "Luke",:last_name => " Mack");user = users[200]; user.avatar_remote_url('http://lorempixel.com/300/260/', user.slug); user.save

# Post.create(:user_id => user.id, :title => "Savory Summer: Week 2 at Coolhouse Labs", :content => 
# 	"We’re playing catch up, so here’s a peek into our second week at Coolhouse Labs through the meals we’ve shared. What better way to start off the week than with some farm fresh eggs! Delivered via woven basket by the librarian, the Coolhouse cohort divvied them up.
# 	A few days later we met with Eric Liberman for lunch at Turkey’s Cafe & Pizzeria on Main Street. We all ordered the Garden Burger, a veggie burger with lettuce, tomato, onions and pickles. It did not disappoint.
# 	On Friday we traveled to Petoskey, just a 15 minute drive from our home in Harbor Springs. We stopped at the farmer’s market in the morning and were delighted to see a large number of vendors and a sizable crowd.
# 	In the afternoon we met with the good people of American Spoon, a Michigan-made company that’s famous for their fruit preserves. We’ll be blogging about our experience soon, but until then here’s what we tasted at their cafe in Petoskey’s historic Pennsylvania Park. Note that most, if not all, items on the menu are prepared seasonally with ingredients from local farmers and foragers!
# 	May I also note that the Strawberry Mint sorbetto was indeed the best thing I have tasted thus far in Michigan. Not only was it perfectly refreshing for a summer day, I also found out that one of the owners Justin Rashid had gathered the wild mint recently on one of this foraging trips.")
# Post.create(:user_id => user.id, :title => "Savory Summer: Week 1 at Coolhouse Labs", :content =>
# 	"In an effort to document our experience this summer, we’ll be writing a series of blog posts about life in Harbor Springs. And what better way to document this experience than to show you the meals we share with the people around us. After all, meals are often the most enjoyable and memorable part of our days. Amirite?
# 	Harbor Springs is an idyllic city. Small shops, local businesses,  and family stores line the main street. Then of course there’s the Coolhouse Labs co-working space – a little reminder of the big city in this small town. “The lab”, as I like to call it, has a bright and open floor plan that encourages us to use our fellow companies as a sounding board.
# 	We arrived Sunday night, so Todd, Al, and I had a team dinner at our new house.
# 	The first day in the lab was like the first day at summer camp. There were nerves, there was excitement, and there was outdoor activity. As a team-building/ice-breaking experiment, Coolhouse challenged each team to brand their own bottled water and sell it on the streets of Harbor Springs. We had 45 minutes to come up with a brand, and 45 minutes to sell the water. While we may not have won for branding (shoutout to TRNK New York), we did raise the most money.
# 	The evening ended with a group dinner on the lake. Great friends, a beautiful sunset, and of course a delicious meal!
# 	The next few days we’re spent working on our pitch and initial strategy in preparation for a slew of mentor meetings we’d be having the rest of the week. One of our favorite aspects of the program thus far has been the access to some really COOL mentors. From VCs to past startup CEOs the list of mentors is diverse, and is giving the teams here a variety of perspectives — all very helpful.
# 	Wednesday morning was our first taste of the local farmers market, which had over a dozen different stands. We bought some seedlings for the backyard garden we wanted to plant and talked to the producers. We also stocked up on some fresh veggies for dinner. Since we hadn’t had a chance to get to know our housemates yet, we planned a “family cookout” on the patio.
# 	All week we had been hearing about Pond Hill farm, so on Saturday we drove over to the farm for a pig roast. We talked with the owner Jimmy, got an intro to the local wine by the bartender, and enjoyed a wonderful buffet outside on the patio.")