require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlotCropVarietiesController do

  # This should return the minimal set of attributes required to create a valid
  # PlotCropVariety. As you add validations to PlotCropVariety, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlotCropVarietiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all plot_crop_varieties as @plot_crop_varieties" do
      plot_crop_variety = PlotCropVariety.create! valid_attributes
      get :index, {}, valid_session
      assigns(:plot_crop_varieties).should eq([plot_crop_variety])
    end
  end

  describe "GET show" do
    it "assigns the requested plot_crop_variety as @plot_crop_variety" do
      plot_crop_variety = PlotCropVariety.create! valid_attributes
      get :show, {:id => plot_crop_variety.to_param}, valid_session
      assigns(:plot_crop_variety).should eq(plot_crop_variety)
    end
  end

  describe "GET new" do
    it "assigns a new plot_crop_variety as @plot_crop_variety" do
      get :new, {}, valid_session
      assigns(:plot_crop_variety).should be_a_new(PlotCropVariety)
    end
  end

  describe "GET edit" do
    it "assigns the requested plot_crop_variety as @plot_crop_variety" do
      plot_crop_variety = PlotCropVariety.create! valid_attributes
      get :edit, {:id => plot_crop_variety.to_param}, valid_session
      assigns(:plot_crop_variety).should eq(plot_crop_variety)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlotCropVariety" do
        expect {
          post :create, {:plot_crop_variety => valid_attributes}, valid_session
        }.to change(PlotCropVariety, :count).by(1)
      end

      it "assigns a newly created plot_crop_variety as @plot_crop_variety" do
        post :create, {:plot_crop_variety => valid_attributes}, valid_session
        assigns(:plot_crop_variety).should be_a(PlotCropVariety)
        assigns(:plot_crop_variety).should be_persisted
      end

      it "redirects to the created plot_crop_variety" do
        post :create, {:plot_crop_variety => valid_attributes}, valid_session
        response.should redirect_to(PlotCropVariety.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved plot_crop_variety as @plot_crop_variety" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlotCropVariety.any_instance.stub(:save).and_return(false)
        post :create, {:plot_crop_variety => {  }}, valid_session
        assigns(:plot_crop_variety).should be_a_new(PlotCropVariety)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlotCropVariety.any_instance.stub(:save).and_return(false)
        post :create, {:plot_crop_variety => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested plot_crop_variety" do
        plot_crop_variety = PlotCropVariety.create! valid_attributes
        # Assuming there are no other plot_crop_varieties in the database, this
        # specifies that the PlotCropVariety created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlotCropVariety.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => plot_crop_variety.to_param, :plot_crop_variety => { "these" => "params" }}, valid_session
      end

      it "assigns the requested plot_crop_variety as @plot_crop_variety" do
        plot_crop_variety = PlotCropVariety.create! valid_attributes
        put :update, {:id => plot_crop_variety.to_param, :plot_crop_variety => valid_attributes}, valid_session
        assigns(:plot_crop_variety).should eq(plot_crop_variety)
      end

      it "redirects to the plot_crop_variety" do
        plot_crop_variety = PlotCropVariety.create! valid_attributes
        put :update, {:id => plot_crop_variety.to_param, :plot_crop_variety => valid_attributes}, valid_session
        response.should redirect_to(plot_crop_variety)
      end
    end

    describe "with invalid params" do
      it "assigns the plot_crop_variety as @plot_crop_variety" do
        plot_crop_variety = PlotCropVariety.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlotCropVariety.any_instance.stub(:save).and_return(false)
        put :update, {:id => plot_crop_variety.to_param, :plot_crop_variety => {  }}, valid_session
        assigns(:plot_crop_variety).should eq(plot_crop_variety)
      end

      it "re-renders the 'edit' template" do
        plot_crop_variety = PlotCropVariety.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlotCropVariety.any_instance.stub(:save).and_return(false)
        put :update, {:id => plot_crop_variety.to_param, :plot_crop_variety => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested plot_crop_variety" do
      plot_crop_variety = PlotCropVariety.create! valid_attributes
      expect {
        delete :destroy, {:id => plot_crop_variety.to_param}, valid_session
      }.to change(PlotCropVariety, :count).by(-1)
    end

    it "redirects to the plot_crop_varieties list" do
      plot_crop_variety = PlotCropVariety.create! valid_attributes
      delete :destroy, {:id => plot_crop_variety.to_param}, valid_session
      response.should redirect_to(plot_crop_varieties_url)
    end
  end

end
